### ISSUE TITLE
weird node-gyp issue at v 6.0.1

### ISSUE THREAD

**Issue by ubidefeo** [WebReflection/archibold.io#12]
I have bumped into a weird one (always me) which escalated into madness.

node version 13.6.0
npm version 6.13.4

Essentially I could not install my app (`package.json` to follow) because it required `node-gyp` to find the right version of python (not 2.x but 3.x) and then complaining about still not being able to do `node-gyp rebuild`.

here's an extract of the error from the `--verbose` log:

```
gyp verb find Python checking Python explicitly set from command line or npm configuration
gyp verb find Python - "--python=" or "npm config get python" is "python2"
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - executable path is "/usr/bin/python2"
gyp verb find Python - executing "/usr/bin/python2" to get version
gyp verb find Python - version is "2.7.17"
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Class constructor Range cannot be invoked without 'new'
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/node-gyp/lib/find-python.js:229:28)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/node-gyp/lib/find-python.js:274:7)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:7)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:443:11)
gyp ERR! stack     at Socket.emit (events.js:321:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:668:12)
gyp ERR! System Linux 4.19.93-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alarm/node_modules/@serialport/bindings
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

my package.json is as follows
```JSON
{
  "name": "bett2020",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "install": "electron-rebuild",
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^7.1.7",
    "serialport": "^8.0.6"
  },
  "devDependencies": {
    "electron-rebuild": "^1.8.8"
  }
}
```
after a long series of searches, readings and the usual cussing I decided to attempt installing Python 3.x and link it as the right Python for `npm` to use, and because after instaling 3.8.1 it was automatically linked to be the default Python binary we can refer to it simply as `python` when setting the config for npm.

```
[alarm@alarm ~] pacman -S python3
...
...
[alarm@alarm ~] npm config set python python
```

after this I kept getting the same issue, but of course the correct version of Python was part of the above error's output: the culprit must be `node-gyp` version 6.0.1 at this point... it can't be anything else.
I struggle to accept that I cannot install the latest version of a package on Arch, but I realised that despite me still not understanding the whole `npm` way of life, I could simply install the latest `node-gyp` by simply

```
[alarm@alarm ~] npm i -g node-gyp
```

this installed version 6.1.0 in `/home/alarm/.npm-packages/bin/node-gyp`, and I could finally

```
[alarm@alarm ~] npm config set node-gyp /home/alarm/.npm-packages/bin/node-gyp
```
after this step my installation worked and I could install all my modules and binaries in the home folders' `.npm-packages` and `node_modules`.
I confess I still don't get it, but I guess being this my very first Node+Electron project I'm doing better than I would expect.

Hope the above infos help someone running into similar issues.
I think B.E.N.J.A. is a great idea and it can go very far, but some more detailed information is required to get regular Debian/Raspian users into how and why the system is setup this way as well as giving a better run down of what exactly happens when the system is setup and run.

Loving the learning curve so far. I'm joking... it's a learning wall :D

**Comment by WebReflection** [comment]
to start with, I think Python3, being the default, is installed by default. If that's not the case, I can explicitly install it in the automated procedure.

However, I think the main mistake here is that you put electron and serialport in your package.json, while both are already present in the BENJA user folder (alarm by default).

As I don't know why you need electron-rebuild neither, as compiling stuff in the Pi is not usually the Pi way to go, I am not sure I can suggest to drop everything from your package.json (dependencies and devDependencies), but I believe with a clean install of BENJA, your project would work just fine without those.

Last, but not least, BENJA is an installer and nothing else. Once you install it, and it works, its job/responsibility is completed.

From that time on, you're on ArchLinux ARM world, and there is a forum full of people willing to help.

The learning curve is about how linux, nodejs, and npm, within node-gyp, work together, but I wouldn't blame BENJA for that, as BENJA is the enabler, not the manager of these programs.

**Comment by ubidefeo** [comment]
hey @WebReflection 
I'm sure there's something wrong on my side, I'm still learning after all.
Also not blaming BENJA at all, I'm ecstatic about it.

What I'm suggesting is that BENJA could be a great case to start learning how this workflow is structured and how to produce content for it.

I'd love to see a tutorial/walk-through which tells BENJA users how you got there.
I've showed it to my team mates and they all like it.
I hope I can build enough knowledge to be able to contribute to it.

That said, Python2 was default in my install, but maybe now that it's officially sunset (https://www.python.org/doc/sunset-python-2/) Python 3 will be default in Arch (haven't looked).

Thank you so much for your patience, mate.
I love projects which push me into fields I haven't touched yet, and this is definitely one of them :)

**Comment by WebReflection** [comment]
I'm fresh-installing on the background to see if python3 gets in ... in ArchLinux, `pacman -S python` already brings in version 3, as that's the default, but many things still use the dead Python 2.

**Comment by ubidefeo** [comment]
I know, but believe me when I say I had to manually install Python 3 as you can read above.
Actually invoking `python` didn't bring anything and `which python` didn't find anything.
I created a temporary alias to `python2` to get it triggered.

I keep believing there's something wrong happening during my provisioning/installing process which hinders parts of the chain while still giving me a functioning BENJA on the Pi 4.
On the Pi 3 I haven't been able to create a single successful SD Card on Mac, but that's for another issue when I have time to mess around with it :)

**Comment by WebReflection** [comment]
BTW, you are right ... they removed Python from the base-devel / default installed applications, which is the ArchLinux way (to be minimalistic) but quite annoying when you trust default apps installed (they recently removed even `vi` from base ArchLinux installation) ... recent changes brings Python3 **and** Python2 in, and I hope this fixes all the gotchas.

**Comment by ubidefeo** [comment]
thank you for checking.
you know, as I age it's easy to start doubting myself and my memory :D

**Comment by WebReflection** [comment]
OK, it looks like node-gyp is incapable of building `@serialport/bindings` needed somewhere with raspi-io ... it also uses a super jurassic version of that, which might be an issue if it needs Python 2 but the rest uses Python 3 ... what a bummer.

**Comment by WebReflection** [comment]
Filed an issue here: https://github.com/nebrius/raspi-serial/issues/10

**Comment by WebReflection** [comment]
FYI, it looks like the issue is with NodeJS 13, as version 12 works just fine.

**Comment by ubidefeo** [comment]
I thought so, but didn't want to downgrade Node yesterday.
I figured the hardest path was the one to choose. :palmface

**Comment by WebReflection** [comment]
so, latest file uses `nodejs-lts-erbium` instead of `nodejs`, that ensures you'll run LTS version of nodejs, which is version 12, which (_should_) compiles raspi-io just fine.

will spin another SD card during lunch, but I think that solves, for the time being.

**Comment by ubidefeo** [comment]
thank you for the hard work
in the meantime I had a colleague give me a crash course in Node/npm and we discussed BENJA a lot :D

**Comment by WebReflection** [comment]
FYI I can confirm no errors is shown anymore building all the things, including serialport, raspi-io, and johnny-five 👋

**Comment by ubidefeo** [comment]
awesome!

**Comment by WebReflection** [comment]
Still remember to never install by yourself these libraries or even electron ... just drop anything that requires node-gyp from your package.json, and use a parent folder on your Mac/Linux/PC if you need those modules.

**Comment by ubidefeo** [comment]
thank you, mate
I have learned a lot already, and I think I get the philosophy behind BENJA much better :)

**Comment by WebReflection** [comment]
FYI the aarch64 installation also has issues due https://archlinuxarm.org/forum/viewtopic.php?f=65&t=14203 ... the node-gyp there is the old one, and it will fail at building anything.

Hopefully it's just a matter of time (hours? days?) before the latest node-gyp is used, and the current procedure would work in RPi3 too.

**Comment by WebReflection** [comment]
P.S. this should fix the issue

```sh
sed -i 's/= semver.Range/= new semver.Range/' /usr/lib/node_modules/node-gyp/lib/find-python.js
```
