### ISSUE TITLE
The long road to GLES2

### ISSUE THREAD

**Issue by ubidefeo** [WebReflection/archibold.io#16]
@WebReflection 
I have been looking at how to implement glesv2 in order to run WEBGL accelerated content and I have to say there's sooooooo much to learn about how Linux and Xorg manage screen output that  I feel that learning tingle :D

Anyway... I have replaced `cairo` with `cairo-gles2-armv7l` (https://aur.archlinux.org/packages/cairo-glesv2-armv7l/) and it installs replacing `cairo` installed by BENJA's setup, but I have incurred into a minor install issue:

`makepkg -si` will return `==> ERROR: cairo-glesv2-armv7l is not available for the 'armv7h' architecture.`

I've looked it up and amongst suggestions there was passing `A` to the command so

`makepkg -siA` did the trick.

I've shipped my game to the faire in London after testing it extensively, so I'd say it's safe to replace `cairo` with `cairo-gles2-armv7l` if you feel comfortable.

u.

**Comment by WebReflection** [comment]
Which platform was it? 'cause the pi4 is in arm7l, so that installing `aur cairo-glesv2-$(uname -m)` should do the trick?

In any case, I'm the Creator and maintainer of that package, so that all I have to do eventually is to add arm7h as potential target. Was this accelerating electron in BENJA?

Thanks for any extra detail you could provide.

**Comment by ubidefeo** [comment]
on Pi4, and nope... no real visible change in speed.
`uname -m` returns the correct `armv7l`, so it's definitely something odd in the build process.

Also I am making progress on the tearing, but I'll post another issue because it's related to using Picom :)

**Comment by WebReflection** [comment]
On a clean install of the ArchLinux for Pi4, try logging in as alarm and `bash <(curl -s https://archibold.io/kiosk/pi/wpe)` ...you'll install the fastest, fully hardware accelerated version on WPEWebKit kiosk, and that module goes in without issues.

**Comment by ubidefeo** [comment]
a-ha!
looking forward to testing in the next 15 minutes

thank you 🙏

**Comment by WebReflection** [comment]
https://youtu.be/T3BdiEe8lqA

**Comment by ubidefeo** [comment]
oh, wow!
I wish you had sent me this earlier during our conversations :D

**Comment by ubidefeo** [comment]
I have ran the installer under a pre-existing BENJA and I think it didn't work out well.
I'll go for a clean install when I have time to make one.
Thank you for all the work, @WebReflection  :)

**Comment by WebReflection** [comment]
armv7h for cairo-glesv2-armv7l is part of the installable architectures.
