### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by robsecord** [WebReflection/archibold.io#17]
What License does this software use?

**Comment by WebReflection** [comment]
I suppose everything I wrote would be under MIT (but I agree, it should be explicit)
Arch Linux itself seems to be under GPL (not sure which version) while the software it carries around can have pretty much any other license.

Does this answer your question? Any part of the software you'd like to know more in particular?

**Comment by robsecord** [comment]
Excellent, would you be able to add a LICENSE file to the root directory, in order to be explicit, and so that derivative works can include a copy of the license, as per compliance?
Greatly appreciated, and I love the project!

**Comment by WebReflection** [comment]
done 👋
