### ISSUE TITLE
Raspbery pi 7" Touchscreen - touch gestures not recognized in weston / cog fullscreen browser gui

### ISSUE THREAD

**Issue by lwlagrange** [WebReflection/archibold.io#20]
Hello,

I have this package installed on arch linux with a raspberry pi 4. I discovered the touchscreen input doesn't support hold ad drag on the COG browser. I tried the [libinput] settings in weston.ini and they didnt seem to do anythning.

I run:
```
libinput list-devices
```
it gets the device name 'raspberrypi_ts' but all the options like Tap-and-drag or Tap-to-click say n/a
Looks like the touchscreen is being identified as a mouse?  or like a laptop touchpad? not sure.

**Comment by WebReflection** [comment]
sounds like a bug for COG then? https://github.com/Igalia/cog
