### ISSUE TITLE
B.E.N.J.A. installer is broken on rpi3

### ISSUE THREAD

**Issue by hedwiggggg** [WebReflection/archibold.io#21]
hi, i've tried to configure an sd card for a raspberry pi 3.

But after a few tries on different OSs, i've thought: "somethings wrong here".

So i've investigated a bit and found out, that `http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz` seems to be no longer existing. It seems to be replaced with `http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz`.

**Comment by WebReflection** [comment]
does that mean both 3 and 4 are finally supported?

**Comment by hedwiggggg** [comment]
Can't really test it, but there are images for RPi ARMv6, RPi  2/3 ARMv7, RPi 4 ARMv7 and RPi 3/4 ARMv8.

**Comment by WebReflection** [comment]
Source changed as `ArchLinuxARM-rpi-aarch64-latest.tar.gz` ... this should now work.
