### ISSUE TITLE
WPE Kiosk booting to black screen

### ISSUE THREAD

**Issue by jcrapsey** [WebReflection/archibold.io#22]
I followed the tutorial for the WPE Kiosk and my Raspberry PI 4 is booting to a black screen. After a bit of debugging I noticed that cog was failing to start with the following error.
```
cog: error while loading shared libraries: libicudata.so.67: cannot open shared object file: No such file or directory
```
It looks like icu was updated to 68 recently.

**Comment by WebReflection** [comment]
did you use `bash <(curl -s https://archibold.io/kiosk/pi/wpe)` ?

in any case, I am abroad and I don't have my Pi with me, so if you find the culprit, PR welcome.

**Comment by jcrapsey** [comment]
Yes I did, It looks like I may have to recompile either cog or wpe with the new version of libicu (those were the closest solutions to this problem while searching). I'll update if I make any progress.

**Comment by WebReflection** [comment]
the script compiles already cog and wpe, if I remember correctly, but yeah ... if you find any solution, it'd be great.

I was waiting for wpewebkit 2.32 to go out, as it takes forever to build it on the Pi, but I see 2.30.4 has been published, and maybe that fixed this issue you are having: https://aur.archlinux.org/packages/wpewebkit

still, until I'm back home, I can't do much, sorry.

**Comment by jcrapsey** [comment]
I was able to compile wpewebkit 2.30.4 on my raspberry pi and it works!
Looks like wpewebkit-bin needs to be updated to this version to support libicu 68

**Comment by WebReflection** [comment]
tomorrow I'll fly back home and by Monday evening I should be able to have it built and updated, thanks for confirming 👋

**Comment by WebReflection** [comment]
2.30.4 is up ... I hope running too
