### ISSUE TITLE
A RPi kiosk doesn't  boot

### ISSUE THREAD

**Issue by gev** [WebReflection/archibold.io#23]
Hi Andrea!

I'd try to make a kiosk by your post https://webreflection.medium.com/ive-found-the-time-to-create-a-wpewebkit-based-kiosk-for-raspberry-pi-4-the-3-has-issues-with-3a651f0f320e 
After installing wpewebkit 
```
bash <(curl -s https://archibold.io/kiosk/pi/wpe)
```
and  restarting RPi doesn't boot at all

Any idias?

--
Evgeny

**Comment by alwinlubbers** [comment]
It looks like the link for downloading the RPi4 image is dead, it does not work for me either. It just partitions the drive and that's it. The OS won't download. The other ones work 'fine', the 64-bit image does download and boots (sort of) but after boot it keeps telling "mmcl error -22".

**Comment by WebReflection** [comment]
there have been changes in the 64bit version of the OS and I didn't get a chance to test those ... yet nobody in here wrote which version of the board are you using.

@alwinlubbers I have no idea what you are also talking about, but no ISO exists anymore, so I won't likely help there.

**Comment by alwinlubbers** [comment]
Hi there @WebReflection ,
The tool provided on the website (bash script) asks which version you’d like to download, as far as i can tell, the files for the fourth option won’t download. So what you’ll get is a blank SD card with a couple of partitions, but no files. 

I’m using a Raspberry Pi 4B 4GB with a Samsung Evo Plus 32GB SD card. Thanks for the quick response.

**Comment by WebReflection** [comment]
[this file](https://github.com/WebReflection/archibold.io/blob/master/kiosk/pi/wpe) doesn't ask for anything ... but maybe you are talking about B.E.N.J.A. which is completely different?

**Comment by lmckeen** [comment]
I had a similar issue and have yet to find a solution... it was caused by weston not respecting the require-input=false configuration value... I was able to get the device to boot if a keyboard was also plugged into my raspberry pi before booting

**Comment by WebReflection** [comment]
Please comment out or remove `enable_uart=1` in the `/boot/config.txt` file or try again to install from *archibold.io* as that was needed at some point but it's causing kernel panic now

**Comment by alwinlubbers** [comment]
> [this file](https://github.com/WebReflection/archibold.io/blob/master/kiosk/pi/wpe) doesn't ask for anything ... but maybe you are talking about B.E.N.J.A. which is completely different?

Excuse me, you're right. Somehow ended up in the wrong repo. I was indeed my question is indeed related to B.E.N.J.A.. I'm sorry.

**Comment by WebReflection** [comment]
@alwinlubbers 

> Somehow ended up in the wrong repo.

this is the right repo, it's just one repo that contains **a lot** of stuff ... [including BENJA](https://github.com/WebReflection/archibold.io/tree/master/benja#readme) ... but these days BENJA is inferior to the WPEWebKit Kiosk mentioned in here, which is fully HW accelerated, plus with projects like [electroff](https://github.com/WebReflection/electroff#readme) or [proxied-node](https://github.com/WebReflection/proxied-node#readme) the clunky Electron on Pi can be easily replaced.
