### ISSUE TITLE
Initial setup hits a loop and doesn't finish setup

### ISSUE THREAD

**Issue by spencer-hill** [WebReflection/archibold.io#24]
After creating the SD card for a Raspberry Pi 4 and logging into the pi, the setup script runs until it hits a point and loops over this set in the terminal (See output below). I've tried on both a Pi 2 and 4 with multiple sd cards. Seems like an issue with the package libcanberra-gstreamer? Im really interested in this project and want to try it out.

`warning: nss-3.72-1 is up to date -- skipping\
warning: libva-vdpau-driver-0.7.4-5 is up to date -- skipping\
warning: libva-mesa-driver-21.2.5-1 is up to date -- skipping\
error: target not found: libcanberra-gstreamer\
warning: c-ares-1.18.1-1 is up to date -- skipping\
warning: libnghttp2-1.46.0-1 is up to date -- skipping\
warning: nss-3.72-1 is up to date -- skipping\
warning: libva-vdpau-driver-0.7.4-5 is up to date -- skipping\
warning: libva-mesa-driver-21.2.5-1 is up to date -- skipping\
error: target not found: libcanberra-gstreamer\
warning: c-ares-1.18.1-1 is up to date -- skipping\
warning: libnghttp2-1.46.0-1 is up to date -- skipping\
warning: nss-3.72-1 is up to date -- skipping\
warning: libva-vdpau-driver-0.7.4-5 is up to date -- skipping\
warning: libva-mesa-driver-21.2.5-1 is up to date -- skipping\
error: target not found: libcanberra-gstreamer\
warning: c-ares-1.18.1-1 is up to date -- skipping\
warning: libnghttp2-1.46.0-1 is up to date -- skipping\
warning: nss-3.72-1 is up to date -- skipping`

**Comment by ubidefeo** [comment]
Strangest coincidence, @spencer-hill 
I used Archibold 2 years ago for an event and just today wanted to give a shot at running it on the Pi 4.
I'll first try and throw the SD I used for the Pi 3 at a Pi 4 and see what happens :)

**Comment by WebReflection** [comment]
@spencer-hill which project are you referring to? this repo contains **archibold** which is *NOT* meant to run on a Raspberry Pi, but also contains installers for the Kiosk, and the B.E.N.J.A. installer ... are you trying any of these two?

I need to know exactly what command you typed in your Pi, otherwise I can't help much, thank you.

**Comment by spencer-hill** [comment]
@ubidefeo Thanks for any help/insight.
@WebReflection Sorry, you're right. I should have been more clear. This is for B.E.N.J.A. The SD prep script, run with `bash <(curl -s https://archibold.io/benja/prepare)`, completes without issue. Card inserted into the Pi, connect ethernet, boots up and login with the alarm user. Then it automatically runs the bootstrap script, and this is when the issue pops up. It seems like it's moving along as it should; downloading packages, sets default locale, etc. It then hits a point after its downloaded some packages where it loops over the same set error messages (posted above). It seems like its an issue with the package `libcanberra-gstreamer`, but Im not sure.

**Comment by WebReflection** [comment]
@spencer-hill I think I've fixed it ... btw, these days I am using [proxied-node](https://github.com/WebReflection/proxied-node#readme) and [WPEWebKit](https://webreflection.medium.com/a-minimalistic-64-bit-web-kiosk-for-rpi-3-98e460419b47) ... this stuff [runs even on latest Raspberry Pi Zero 2 W at full speed](https://www.youtube.com/watch?v=kkqheU0PnjI) and I suggest to have a look, in case the project is not already fully Electron dependent.

More on my alternatives here: https://webreflection.medium.com/electron-headless-alternatives-f860c28a3ba9

**Comment by spencer-hill** [comment]
@WebReflection  Thank you! I appreciate it. The project I'm working on is an already established codebase in Electron. I'll look into your alternative projects for my future projects!

**Comment by WebReflection** [comment]
@ubidefeo the Pi 3 was 64bit, IIRC, so the current best 64bit for the Pi is via `linux-raspberrypi4` kernel, soon to be renamed, as it runs on Pi 3, Pi 4, and Pi Zero 2 W ... that gives you HW acceleration on the Pi 4, but I haven't had the time to update BENJA to this setup.

I think it's about the time though, and I'll remove everything that is **not** 64 bit, providing a single BENJA experience for all modern/recent Raspberry Pi variants, which are all 64bit capable.

**edit** if you are planning to try the new kernel ssh into it and run:
```sh
bash <(curl -s https://archibold.io/install/linux-raspberrypi)
```
as just installing the right module is not enough
