### ISSUE TITLE
re: how to install archlinux from scratch article

### ISSUE THREAD

**Issue by bitflame** [WebReflection/archibold.io#27]
Hi 
I want to thank you for the article on freecode camp, and I do have a couple of questions please. 1- You said once you log in to your account issue commands. I am assuming you meant once I boot into the live usb? and 2- If I am doing this from a location that needs me to accept the wifi policy by clicking on a button of a web page, can I still follow your instructions? 
lastly I want to say I appologize if I am in the wrong place. I followed the link that was provided on the article.

**Comment by WebReflection** [comment]
Can’t remember point 1 to be honest, but about point 2 … I never installed any Linux at the airport, but I guess graphic installers would handle that … although these days there’s an official archinstall command that would provide almost everything I’ve mentioned in those days, and hopefully handles those cases too … have you tried it? Otherwise I’m afraid I don’t have a solution here, neither ever facing that use case

**Comment by bitflame** [comment]
Hi Thank you so much. I'll give it a shot in a few minutes. I have not tried it yet.

**Comment by bitflame** [comment]
I downloaded, and created the usb, and am about to test it. I wanted to share some suggestions in case they are helpful. The wiki content is great. Some details that could be useful for me are: 
Name torrent clients we can use on Linux and Windows 
sq command does not work on Fedora 36. I did check Fedora magazine for both of these to find the same or similar tool but could not find any. I am so appreciative to folks like yourself who spend their time putting together the content. I hope that these suggestions will help more people get started with this distro. It has been my experience that I have to use Fedora specific content to get things done on it, and most of the time I can not use vanilla Linux commands. But Fedora magazine and the askfedora just rocks, and I've been able to get done what I want with the content they have and understand what I am doing.

**Comment by WebReflection** [comment]
Mate, I use archibold for myself and I’m happy to share its installer but it’s definitely not a mainstream installer or config, just my ArchLinux and GNOME flavor with 100% encryption. Transmission is the torrent client of my choice, every other software can be searched through GNOME or pamac

**Comment by bitflame** [comment]
Thank you so much. I think I should just keep trying and learn.

CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s)
and may contain confidential and/or privileged information and may be legally protected from
disclosure. If you are not the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by reply email and then
delete this message and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
