### ISSUE TITLE
WPE Kiosk failing to run after update

### ISSUE THREAD

**Issue by JoshAntBrown** [WebReflection/archibold.io#29]
I updated my system a few days ago after setting up WPE Kiosk a month ago.

It seems the recent versions have broken a few things.

First, I needed to install libdisplay-info, which is a new optional dep required for weston to use the drm backend (https://bbs.archlinux.org/viewtopic.php?id=299707).

After installing libdisplay-info cog seems to hang on a black screen, and while cog and WPEWebProcess are running the entire system becomes very sluggish until the processes are killed. In the meantime I've switched over to using chromium but it's performance doesn't seem as good as what I had before with cog and wpewebkit.

**Comment by WebReflection** [comment]
yeah, I've noticed the same after a weston update ... thanks for the news `libdisplay-info` might fix it, but I am afraid I don't control anything happening in there so ... update cog and try again? If that doesn't work, I have no idea how to help if weston and cog keep shipping updates in such unstable ways 😥

**Comment by WebReflection** [comment]
I've played around on both Pi4 and Pi5 (which still require initial install in a Pi4 then once the `linux-rpi` is in works well in the Pi5 too).

With this file and the following insturctions you should be able to login as alarm and bootstrap weston terminal right after: https://github.com/WebReflection/archibold.io/blob/master/init-pi

```sh
# first boot on a Pi3 or Pi4 - as root
bash <(curl -s https://archibold.io/init-pi)

# once that's done, do whatever you like as root then reboot
# after first run as root, enter as alarm user ... then
bash <(curl -s https://archibold.io/init-pi)
```

Once these two steps are completed, you can reboot as `alarm` and you'll find yourself in weston with a terminal window.

You can edit `.config/weston.ini` there and change the `client=...` to point at `/home/alarm/kiosk` as example, where in there you'll have:

```sh
#!/usr/bin/env sh

cog https://archibold.io/demo/jellyfish/
```

Remember to `chmod +x ~/kiosk` and reboot ... this time you'll find yourself in fullscreen with a WebGL demo running at 20 to 60 FPS, it depends on your device/HW.

From there, you have an entry point to do whatever you like with `cog` and you can play around display resolution in your `~/.bashrc`, still as `alarm` user.

**Comment by WebReflection** [comment]
P.S. I've noticed that without `ttf-dejavu` I had blank screen ... I hence decided to add it but also I've added noto-fonts which brings in emoji too and the whole thing should run smoothly after. Also remember latest ArchLinuxARM on Pi requires 512MB of boot partition so if you were using 100M or 200M I have a bad news for you.

**Comment by JoshAntBrown** [comment]
Thanks so much tracking down the issues, all works after installing those dependencies.

Fortunately I'd already ran into the boot partition issue so gave myself some extra space ahead of time.
