### ISSUE TITLE
How to install on Intel Compute Stick (STCK1A32WFCR)?

### ISSUE THREAD

**Issue by bkhl** [WebReflection/archibold.io#3]
Hello,

I've tried booting the Arch installer on an Intel Compute Stick (STCK1A32WFCR) with a normal dd-created USB flash installation medium, but having no luck. The boot menu does not list the device.

I've had to connect the USB flash drive through a USB hub in order to also connect a keyboard so that I'll even get to the boot menu.

As your web page says someone has been able to do this using Archibold, I'm hoping you have some pointers on how to create the installation medium.

**Comment by WebReflection** [comment]
That "someone" is me :-)

I've used this hub: http://www.ianker.com/USB-Data-Hubs/category-c11-s1

You need an active one or the compute stick won't be able to give enough power for both keyboard and flash drive.

You also need to be sure you have the latest firmware
8GB https://downloadcenter.intel.com/product/86613/Intel-Compute-Stick-STCK1A8LFC
32GB https://downloadcenter.intel.com/product/86612/Intel-Compute-Stick-STCK1A32WFC

IIRC (I don't have the compute-stick with me at the moment) you need to play a bit with boot options also eventually disabling secure boot (enabling legacy) and once booted via ArchLinux you can `SWAP=1GiB GNOME=NOEXTRA USER=intel PASSWD=intel DISK=/dev/mmblk0 sh archibold.sh` but only after you've used `wifi-menu` to conect to the internet.

Hope this helped
