### ISSUE TITLE
kiosk/rpi3 || test/gjs - video tag will not show video

### ISSUE THREAD

**Issue by rip3rs** [WebReflection/archibold.io#4]
Hi,

I created a simple **index.html** with just a video element, as I could not seem to make videos play.
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
	</head>
	<body>
		<video autoplay muted controls src="https://path/to/mp4/file.mp4"></video>
	</body>
</html>
```

I was able to see the player controls by right clicking on it, the video player is playing something, I believe it is playing the video but no video is shown or sound comes out.

in the terminal the only error I get is:
`$> AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Invalid argument`

as I can see this is sound drivers, thus not thinking this is a problem.

I can't seem to figure out a video log.
This is the Xorg log file might help on anything:

```
192.168.70.�X�Z92.168.70.[root@alarm log]# tail Xorg.1.log
[ 61927.499] (II) No input driver specified, ignoring this device.
[ 61927.499] (II) This device may have been added with another device file.
[ 61927.499] (II) config/udev: Adding drm device (/dev/dri/card0)
[ 61927.500] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 61927.500] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 61927.638] (II) event3  - RC for vc4: device removed
[ 61927.700] (II) event0  - SIGMACHIP Usb Mouse: device removed
[ 61927.744] (II) UnloadModule: "libinput"
[ 61927.745] (II) UnloadModule: "libinput"
[ 61927.861] (II) Server terminated successfully (0). Closing log file.
```

**Comment by WebReflection** [comment]
mind if I ask why are you opening this here?

this repository is about a Linux installer with some software / utility shortcut and I will not provide support for ArchLinux in general in here.

There is the ArchLinux forum, or the ArchLinuxARM forum for that.

Apologies if this is not the answer you were looking for, but I really don't have time to do this.

**Comment by WebReflection** [comment]
P.S. btw, since youtube somehow shows videos, I believe it's a matter of format.

Yet you are using probably WebKitGTK+ so that maybe they know more, otherwise I do suggest to join ArchLinuxARM forum/community, they know much more than I do for specific platforms such the Raspberry Pi itself.

Last, but not least, it looks like it's alsa issue, so a sound issue, not only a video one.

**Comment by rip3rs** [comment]
Hey mate,

Apologies I was not sure where to post this.

Thank you for all of the information. I will ask and search more thoroughly, When I find out I will post my findings to better improve on this.

Again apologies and thanks your awesome! :)

**Comment by WebReflection** [comment]
I'm really sorry for not being a great help, and I know it's about something I've posted ... but Linux is a very big world and there's no way I can start doing this here.

Thanks for your understanding!
