### ISSUE TITLE
A way to get install scripts from within blacklisted networks

### ISSUE THREAD

**Issue by r0mflip** [WebReflection/archibold.io#6]
f***ing captchas (really starting to hate them) wont let me do anything. Please provide a way [similar to](https://github.com/creationix/nvm#install-script) the guys at `nvm` who provide a AIO script to get things done.

**Comment by WebReflection** [comment]
I've no idea what you are talking about.

**Comment by r0mflip** [comment]
Umm, sorry for the rant (and the language).

When Iam behind a network where most people search only for pirated software then google blacklists the network. I assume `archibold.io` is backed by cloudflare which uses captchas to prevent scraping and stuff. So when I run `curl -s archibold.io/base` all I get is HTML.

`nvm` guys provide their install script directly from github (which wont block with google captchas), the installation would succeed in any kind of rouge networks. I would love to find a similar thing.

I can switch to a non-blacklisted network, but then I have a data cap.

**Comment by r0mflip** [comment]
I can have the `base` file from github but then it again fetches other scripts from `archibold.io`. I can get all the files and edit them in place but thats a hassle. A single file with all the scripts would help very much.

**Comment by WebReflection** [comment]
> A single file with all the scripts would help very much.

that's not going to happen. There are dozen scripts and utilities, some interfere with each other, and the structure is modular on purpose.

I might use explicit GitHub resources but so far I've used archibold everywhere in every country I've visited and never had an issue.

The project is also here as a way to learn what's needed or how to install ArchLinux, it's not a service to abuse 'cause I am spending also zero money to have this online and it'll keep staying that way.

There are two options, since you are the only one with this issue:

  * you configure your network to not bother with archibold.io domain
  * you file a PR with all the scripts pointing at their raw GitHub counterpart so your router/network won't bother

**Comment by WebReflection** [comment]
P.S. actually I am spending money for the domain, but nothing else really, and nobody is donating anything to this project so ... I won't put extreme effort to make it work everywhere simply 'cause I have hundreds projects on GitHub and this is not a priority for me, rather an hobby or side project for me, my friends, and my family (plus contributors, of course, but people usually just rant without contributing much).

Thanks for your understanding.

**Comment by r0mflip** [comment]
I can understand 😄


> you configure your network to not bother with archibold.io domain

BTW my whole network (by which I mean my ISP's whole network range) would be bothered by captchas  every single time. This is what I get when I type `curl -s archibold.io/base`

![image](https://user-images.githubusercontent.com/37770235/44955378-e9df7800-aecf-11e8-8fd5-a0a74e7927ac.png)

And it totally works fine when I get pass any cloudflare site in my browser.

> you file a PR with all the scripts pointing at their raw GitHub counterpart so your router/network won't bother

By which do you mean that I make a PR or a gist of the single file and use it?

**Comment by WebReflection** [comment]
out of curiosity, have you tried to simply put `https://` in front of your requests ?

**Comment by r0mflip** [comment]
> out of curiosity, have you tried to simply put https:// in front of your requests ?

It's inconsistent

**Comment by WebReflection** [comment]
what do you mean? I've refactored everything to always use `https://` upfront, which part is not consistent?

**Comment by r0mflip** [comment]
Sorry, my bad. Its working totally fine. I missed the commit.
