### ISSUE TITLE
Official Raspberry Pi Touch Display not working with Web Kiosk

### ISSUE THREAD

**Issue by niklashigi** [WebReflection/archibold.io#7]
Hey Andrea, I'm sorry that I have to bug you with this but I've been trying to get your [Minimalistic 64 bit Web Kiosk for RPi 3](https://medium.com/@WebReflection/a-minimalistic-64-bit-web-kiosk-for-rpi-3-98e460419b47) to work with the [official *Raspberry Pi Touch Display*](https://www.raspberrypi.org/products/raspberry-pi-touch-display/) for weeks now and I'm completely out of ideas. While everything is working on my HDMI monitor (the demo page shows up), when using the touch screen I'm experiencing some very weird behavior:

- the colored rectangle, the "boot logs" and the "Tux screen" screen show up as expected
- but then:
  - the screen turns black
  - it slowly becomes brighter until it is filled with a weird pattern consisting of parallel, grey and white, 2px-wide lines

The screen is definitely not broken since everything before that including the colored rectangle works perfectly. It also worked back when I was using Benja for my project.

Is the touch screen even *supposed* to work after running your kiosk install script or is there something I have to configure/install? How did you get the screen to work by default in Benja?

**Comment by niklashigi** [comment]
I have kind of fixed this problem by simply switching to Raspbian.

**Comment by WebReflection** [comment]
you probably just needed to change the config file to enable the screen, but the kiosk, as explained, would work in any distro so happy you fixed.

I'm still on vacation, which is why I didn't come back.

**Comment by niklashigi** [comment]
> I'm still on vacation, which is why I didn't come back.

I totally understand that. Enjoy the rest of it!
