### ISSUE TITLE
Trouble on Raspberry Pi 4 connecting via WiFi

### ISSUE THREAD

**Issue by ubidefeo** [WebReflection/archibold.io#8]
At first launch I could not get to the automatic setup.
The `bootstrap` process always failed to retrieve `OK` and went into `wifi-setup` again.
I found out that `resolvconf` has an issue reading from `resolvconf.conf` stating that `static` is an unknown command.

I repeated the provisioning process from scratch but got the same result.
The issue seems to be DNS related, because I could ping `8.8.8.8` but not domain names, which made it fail here

```bash
if [ "$(curl -Ls http://archibold.io/OK)" != "OK" ]; then
  ./wifi-setup
fi
```

I eventually plugged in an Ethernet cable and relaunched `bootstrap`.
It is now progressing :)

**Comment by ubidefeo** [comment]
for some reason I ended up posting issues to the wrong repo.
closing.

**Comment by WebReflection** [comment]
@ubidefeo this is the right repository, as the other one got archived. The DNS gotcha happens from time to time, and it could be WiFi router related. Via wired connection, if you have some, there should never be a problem, but it's true I should likely force some different DNS provider out of the box, so that this issue would occur less.

**Comment by ubidefeo** [comment]
that would be amazing, @WebReflection 
in the end I've only tried at home, where I have a Mikrotik managing the network and it can be pretty strict with some stuff :)

**Comment by joshuakarjala** [comment]
I have the same issue - endless loop

**Comment by WebReflection** [comment]
@joshuakarjala then use a network cable, as it's the easiest way to go, 'cause I've no idea why your router wouldn't let the Pi connect (or try changing DNS)
